### ISSUE TITLE
Cannot read contents from file

### ISSUE THREAD

**Issue by CajuCLC** [fballiano/docker-magento2#20]
Hi there.
I have tried using this repo with Magento EE 2.2.2, but getting this error:
`
Fatal error: Uncaught Magento\Framework\Exception\FileSystemException: Cannot read contents from file "/var/www/html/app/etc/di.xml" Warning!file_get_contents(/var/www/html/app/etc/di.xml): failed to open stream: No such file or directory in /var/www/html/vendor/magento/framework/Filesystem/Driver/File.php:149 Stack trace: #0 /var/www/html/vendor/magento/framework/Filesystem/File/Read.php(100): Magento\Framework\Filesystem\Driver\File->fileGetContents('/var/www/html/a...', NULL, NULL) #1 /var/www/html/vendor/magento/framework/Config/FileIterator.php(71): Magento\Framework\Filesystem\File\Read->readAll() #2 /var/www/html/vendor/magento/framework/Config/Reader/Filesystem.php(146): Magento\Framework\Config\FileIterator->current() #3 /var/www/html/vendor/magento/framework/Config/Reader/Filesystem.php(130): Magento\Framework\Config\Reader\Filesystem->_readFiles(Object(Magento\Framework\Config\FileIterator)) #4 /var/www/html/vendor/magento/framework/App/ObjectManagerFactory.php(275): Magento\Framework\Config\Reader\Filesystem-> in /var/www/html/vendor/magento/framework/App/ObjectManagerFactory.php on line 277`

Windows 10 (using Powershell or WSL). Folder has all permissions.

**Comment by CajuCLC** [comment]
BTW, I am getting same error using Magento 2.2.4 that I downloaded from Magento.

**Comment by Dnyomo** [comment]
@CajuCLC Were you able to find an solution to this problem? I am seeing the same problem with 2.2.5.

**Comment by clifinger** [comment]
No news ?

**Comment by CajuCLC** [comment]
No update from me, I honestly just decided to build my own Docker. :)

**Comment by fballiano** [comment]
sorry guys I don't have a windows machine to try it, it never happened to me on mac (although I've to say I don't use it that much)

**Comment by clifinger** [comment]
It work for me  with docker-sync and WSL. My repo based on Laradock: [Magento2onwindows](https://github.com/clifinger/Magento2onwindows)
I followed [docker-sync-on-Windows]( https://github.com/EugenMayer/docker-sync/wiki/docker-sync-on-Windows). I start Magento on Windows by WSL `./sync.sh nginx mysql phpmyadmin`. I will clean later but it work ! I can even change the user permissions inside the volume.  You have this problem because you use CIFS when you share a volume on Docker for Windows don't support chmod ! With docker-sync the volume will be available to be acceded on Windows but the storage will be on WSL so full speed like native Linux ...  Just don't forget to put a :no-copy to not have double writing.

**Comment by fballiano** [comment]
is this still an issue on windows? i was trying to test it but docker needs windows pro or enterprise which I don't have
